// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:2e94e157-b315-4d3c-af58-814c9485683c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_o91hkxa7H",
    "aws_user_pools_web_client_id": "46r0r32kta104qup0ibjbcoe26",
    "aws_appsync_graphqlEndpoint": "https://iv4v7zdyabfg3gdhmlucmgzg24.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_user_files_s3_bucket": "lifestylemed6a375832c546456d80452010981f5b6a",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
